CREATE TABLE IF NOT EXISTS PLAYER (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) UNIQUE,
    NAME VARCHAR(500) NOT NULL,
);
CREATE TABLE IF NOT EXISTS GAME (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PLAYER_ID INT NOT NULL,
    SCORE DOUBLE DEFAULT 0,
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(ID)
);
