CREATE TABLE IF NOT EXISTS PLAYER (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    UID VARCHAR(50) NOT NULL,
    NAME VARCHAR(500) NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    IS_EMAIL_VERIFIED VARCHAR(4),
    ISSUER VARCHAR(50),
    PICTURE VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS GAME (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PLAYER_ID INT NOT NULL,
    SCORE DOUBLE DEFAULT 0,
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(ID)
);
